  version: '3.7'

  services:
    app:
      image: app_vuelos:v2
      container_name: app_vuelos
      build:
        context: ./api-gateway
        dockerfile: Dockerfile
      env_file: .env # Asegúrate de que la ruta sea correcta si el .env está en la carpeta del microservicio
      ports:
        - "80:3000" # Formato correcto para los puertos
      depends_on:
        - mongodb
        - rabbitmq
      restart: always
      networks:
        - ms_nestjs

    microservice-flights:
      image: microservice-flights:v2
      container_name: microservice-flights
      build:
        context: ./microservice-flights
        dockerfile: Dockerfile
      env_file: .env # Cambiado de 'env.file' a 'env_file' y ruta
      restart: always # La indentación debe estar al mismo nivel que 'build' y 'env_file'
      networks:
        - ms_nestjs

    microservice-passengers:
      image: microservice-passengers:v2
      container_name: microservice-passengers_container # Añadido '_container' para evitar conflicto con la imagen:v2
      build:
        context: ./microservice-passengers
        dockerfile: Dockerfile
      env_file: .env # Cambiado de 'env.file' a 'env_file' y ruta
      restart: always
      networks:
        - ms_nestjs

    microservice-users:
      image: microservice-users:v2
      container_name: microservice-users
      build:
        context: ./microservice-users
        dockerfile: Dockerfile
      env_file: .env # Cambiado de 'env.file' a 'env_file' y ruta
      restart: always
      networks:
        - ms_nestjs

    rabbitmq:
      image: rabbitmq:3-management
      container_name: rmq
      ports: # 'expose' solo expone puertos internamente, 'ports' los mapea al host
        - "5672:5672" # Puerto AMQP
        - "15672:15672" # Puerto para la interfaz de administración
      restart: always
      networks:
        - ms_nestjs

    mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment: # Cambiado de 'enviroment' a 'environment'
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - mongodb_data:/data/db # Definido un volumen nombrado para persistencia de datos
      ports: # Para acceder a MongoDB desde tu máquina local si lo necesitas
        - "27017:27017"
      networks:
        - ms_nestjs

  volumes: # Indentación correcta
    mongodb_data: {} # Definición del volumen nombrado

  networks: # Indentación correcta
    ms_nestjs:
      driver: bridge # Opcional: especificar el driver